import type { Metadata } from 'next';
import { Geist, Geist_Mono, Montserrat } from 'next/font/google';
import '@/assets/styles/globals.css';
import GlobalNavigation from '@/components/navigation/GlobalNavigation';
import { NaviListType } from '@/components/navigation/navigation.type';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faFacebookF,
  faGit,
  faLinkedinIn,
  faYoutube,
} from '@fortawesome/free-brands-svg-icons';

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
});
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});
const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Minsoftk's site",
  description: 'Generated by create next app',
};

const mainNaviList: NaviListType[] = [
  {
    key: 'UI 컴포넌트 모음',
    text: 'UI 컴포넌트 모음',
    href: '/ui',
  },
  {
    key: '레이아웃 컴포넌트 모음',
    text: '레이아웃 컴포넌트 모음',
    href: '/layout',
  },
];

const subNaviList: NaviListType[] = [
  {
    key: '깃허브',
    text: '깃허브',
    href: 'https://github.com/minsoftk',
    iconComponent: (
      <FontAwesomeIcon
        color="black"
        icon={faGit}
      />
    ),
  },
  {
    key: '링크드 인',
    text: '링크드 인',
    href: '#',
    iconComponent: (
      <FontAwesomeIcon
        color="black"
        icon={faLinkedinIn}
      />
    ),
  },
  {
    key: '페이스북',
    text: '페이스북',
    href: '#',
    iconComponent: (
      <FontAwesomeIcon
        color="black"
        icon={faFacebookF}
      />
    ),
  },
  {
    key: '유튜브',
    text: '유튜브',
    href: '#',
    iconComponent: (
      <FontAwesomeIcon
        color="black"
        icon={faYoutube}
      />
    ),
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${montserrat.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <GlobalNavigation
            mainNaviList={mainNaviList}
            subNaviList={subNaviList}
          ></GlobalNavigation>
        </nav>
        {children}
      </body>
    </html>
  );
}
